### ISSUE TITLE
기말고사 과제

### ISSUE THREAD

**Issue by niceaji** [advanced-webapps-class/classroom#10]
과제: https://github.com/advanced-webapps-class/classroom/blob/gh-pages/2015/test2.md
제출 메일: kang.daumkakao@gmail.com
제출일: 6월 24일까지 ( 25일에 현재 issue close합니다)
과제질문은 댓글로 주세요~

**Comment by kjh44004** [comment]
예시로 주어진 코드가 에러가 나있는데 에러가 난 상태에서 시작하는 것인가요?

**Comment by SeungW00** [comment]
전체화면기능이 이미되는데 안해도 되는건가요??

**Comment by niceaji** [comment]
@kjh44004 
크롬과 serve 로 띄우면 에러 없습니다. 그래도 발생하면 캡쳐해서 정확히 어떤 에러인지 알려주세요. 
@SeungW00 
전체화면 기능 없는데요? 에디터상에 있는거 얘기하는건가요?  상단에 전체화면 버튼을 만들고 fullscreen api를 사용해서 구현해 주세요

**Comment by kjh44004** [comment]
![image](https://cloud.githubusercontent.com/assets/7088925/8271144/4ce919aa-1843-11e5-8764-1aceb108c975.png)

수정작업 없이 실행만했는데도 에러가 나더군요..

**Comment by niceaji** [comment]
@kjh44004 그냥 파일열기로 열면 당연히 에러가 발생합니다. serve  로 해당디렉토리를 root 로 잡고 개발환경 띄워주세요. :smile:

**Comment by scsc3313** [comment]
js/src/html-editor.js 파일에 summernote부분 모듈화 리팩토링이 정확히 무슨말인가요? ㅠㅠ

**Comment by niceaji** [comment]
@scsc3313 summernote모듈말고 다른 위지윅에디터를 가져다 사용할경우 html-editor.js파일에서만 수정하게끔 하면 모듈화가 될수 있을것 같다..라는 내용 기억나시나요?   summernote초기화 부분등을 html-editor에서 관리하게 하면 좋을것 같네요

**Comment by kjh44004** [comment]
about으로 출력된 레이어는 이후 처리를 어떻게 해야되나요?
1. 시간이 지나면 사라지게 한다
2. 특정 버튼을 눌러닫을수 있게 한다.
3. 영구지속
4. 기타

**Comment by gune1206** [comment]
보안상의 이유로 gmail daum naver 모두 메일이 발송이 제한되고 있는데 어떡해야 하나요??
저도 왜그런지 잘모르겠습니다..

**Comment by gune1206** [comment]
![1111111](https://cloud.githubusercontent.com/assets/7134885/8311838/0950e4d4-1a14-11e5-81e6-a1b4f56dddd1.JPG)

**Comment by harry-jk** [comment]
@gune1206 node_modules폴더를 빼고 압축하시면 됩니다.

**Comment by niceaji** [comment]
@kjh44004 편할대로 처리하면 될듯.. 닫기버튼둬서 닫히게 하던가~ 레이어클릭하면 닫히게하던가.. 가이드가 없는부분은 앱동작에 원할하게만 ~

**Comment by niceaji** [comment]
@gune1206 @jhkang node_modules를 포함하면 메일에서 리젝하나보군요? ;;

**Comment by harry-jk** [comment]
@niceaji 배치파일이 있는 모듈이 있는거 같습니다 :)

**Comment by niceaji** [comment]
@jhkang 아하 :+1:
