### ISSUE TITLE
중간고사 과제

### ISSUE THREAD

**Issue by niceaji** [advanced-webapps-class/classroom#5]
- 과제: https://github.com/advanced-webapps-class/classroom/blob/gh-pages/2015/test1.md
- 제출 메일: kang.daumkakao@gmail.com
- 제출일: 4월 22일까지 ( 22일에 현재 issue close합니다)

과제질문은 댓글로 주세요~

**Comment by caffeine-driven** [comment]
기본적으로 제공된 마크업을 수정해도 되는지 알고싶습니다.

예를들어 현재 li태그에 삽입되어있는 a태그를 삭제가 가능한지 알고싶습니다.

**Comment by niceaji** [comment]
@ghost9087  물론 마크업을 수정해도 됩니다. 
기본제공 마크업은 단순히 도움을  위해서 제공된 거예요.

**Comment by caffeine-driven** [comment]
한가지만 더 질문드리겠습니다^^;
메일 보낼때 압축파일의 파일명은 자유형식인가요 아니면 정해진 형식이 있는것인가요?

**Comment by niceaji** [comment]
@ghost9087  '결과물을 zip으로 압축후 메일로 제출' 이라고 써있네요 :smile:

**Comment by kjh44004** [comment]
과제 조건중 '검색결과에 원본 결과 링크'가 어떤의미인지 알고싶습니다.

**Comment by harry-jk** [comment]
간혹 title이 ""로 비어있는 경우가 있는데 이런 경우에는 그냥 공백으로 표기해야 하나요?

**Comment by niceaji** [comment]
@jhkang 제목이 없으면 빼도 되지않을까요?

**Comment by niceaji** [comment]
@kjh44004 검색 api 를 사용하면  원본콘텐츠의 링크도 나오게 되어있습니다.  link 프로퍼티군요.
참고 : http://developers.daum.net/services/apis/search/board
