### ISSUE TITLE
기말고사 index.html 미리보기 링크가 작동하지 않습니다

### ISSUE THREAD

**Issue by samuelzaza999** [advanced-webapps-class/classroom#78]
https://advanced-webapps-class.github.io/classroom/2022/test2/src

확인해주시면 감사하겠습니다

**Comment by niceaji** [comment]
https://advanced-webapps-class.github.io/classroom/2021/test2/src

일단 이걸로 보시면 됩니다.  

@samuelzaza999

**Comment by samuelzaza999** [comment]
> https://advanced-webapps-class.github.io/classroom/2021/test2/src
> 
> 일단 이걸로 보시면 됩니다.  
> 
> @samuelzaza999

감사합니다.
