### ISSUE TITLE
quiz.json 파일의 previewUrl

### ISSUE THREAD

**Issue by noion0511** [advanced-webapps-class/classroom#79]
중간고사와 기말고사를 위한 레포를 private 상태로 만들었기 때문에 배포할 수 없는 문제가 있는데 공란으로 비워두면 되나요?
그리고 휴강으로 인해서 class.json의 리스트 개수가 14개인데 휴강도 리스트에 포함해야할까요?

**Comment by niceaji** [comment]
@noion0511 네 편하실대로 해주세요. public으로 풀어도 되구요. 휴강포함여부도 원하는대로 해주심되어요 😄

**Comment by noion0511** [comment]
@niceaji 넹 감사합니다.
