### ISSUE TITLE
7번째 과제 

### ISSUE THREAD

**Issue by niceaji** [advanced-webapps-class/classroom#8]
- todo model에  완료여부,등록일 추가  
- todo app에 gruntfile.js , package.json 추가

**Comment by harry-jk** [comment]
2010108174 강진혁입니다.
https://github.com/jhkang/front-end-start/tree/master/07

**Comment by caffeine-driven** [comment]
2010108179 김동하입니다.
https://github.com/ghost9087/front-end-start/tree/master/07

**Comment by sleepbear669** [comment]
2011108182 김재린입니다.
https://github.com/sleepbear669/front-end-start/tree/master/07/todo-webapp-2.0

**Comment by scsc3313** [comment]
2011108209 현승호입니다.
https://github.com/scsc3313/front-end-start/tree/master/07

**Comment by ririthevent** [comment]
2009104138 컴교 김성보입니다.
https://github.com/ririthevent/front-end-start1/tree/master/task7

**Comment by SeungW00** [comment]
2014208010 현승우입니다
https://github.com/SeungW00/front-end-start/tree/master/07/01

**Comment by Wef2** [comment]
2011108181 김보경입니다.
https://github.com/Wef2/front-end-start/tree/master/07

**Comment by kjh44004** [comment]
2011108184 김준호입니다.
https://github.com/kjh44004/front-end-start/tree/master/07

**Comment by Jeongjongho** [comment]
2011104143 정종호입니다.
https://github.com/Jeongjongho/front-end-start/tree/master/07

**Comment by MunheonKang** [comment]
2010108171 강문헌입니다.
https://github.com/kangmunheon/front-end-start/tree/master/07

**Comment by kth9192** [comment]
2011108186

**Comment by kth9192** [comment]
2011108186 김태훈입니다
https://github.com/kth9192/front-end-start/tree/master/07
