### ISSUE TITLE
8번째 과제

### ISSUE THREAD

**Issue by niceaji** [advanced-webapps-class/classroom#9]
game실습내용

**Comment by harry-jk** [comment]
2010108174 강진혁 입니다.

https://github.com/jhkang/front-end-start/tree/master/08

**Comment by caffeine-driven** [comment]
20108179 김동하입니다.

https://github.com/ghost9087/front-end-start/tree/master/08

**Comment by kjh44004** [comment]
2011108184 김준호 입니다.

https://github.com/kjh44004/front-end-start/tree/master/08

**Comment by Wef2** [comment]
2011108181 김보경입니다.

https://github.com/Wef2/front-end-start/tree/master/08

**Comment by sleepbear669** [comment]
2011108182 김재린입니다.
https://github.com/sleepbear669/front-end-start/tree/master/08/pair-card

**Comment by scsc3313** [comment]
2011108209 현승호입니다.
https://github.com/scsc3313/front-end-start/tree/master/08

**Comment by MunheonKang** [comment]
2010108171 강문헌입니다.
https://github.com/kangmunheon/front-end-start/tree/master/08

**Comment by SeungW00** [comment]
2014208010  현승우입니다
https://github.com/SeungW00/front-end-start/tree/master/08

**Comment by JaewonYang** [comment]
2010108199 양재원입니다.

https://github.com/JaewonYang/front-end-start/tree/master/08
